# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: '${{ secrets.DTU_SOC_PUSH_GHA }}'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup node (for xpm)
        uses: actions/setup-node@v2
        with:
          node-version: '21'
      - name: Install xpm
        run: npm install -g xpm@latest
      - name: Install riscv-gnu-toolchain with xpm
        run: |
          xpm install @xpack-dev-tools/riscv-none-elf-gcc@14.2.0-3.1 --verbose --global

      - name: Install verilator
        run: |
          sudo apt-get update -y
          sudo apt-get install verilator -y

      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Run tests
        run: |
          export RISCV_PREFIX="$HOME/.local/xPacks/@xpack-dev-tools/riscv-none-elf-gcc/14.2.0-3.1/.content/bin/riscv-none-elf"
          sbt test

      - name: Build CaravelTopLevel.v and commit to soc-dtu-2025
        run: |
          sbt "runMain CaravelTopLevel"
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          
          ls -R .
          
          cp generated/CaravelTopLevel.v soc-dtu-2025/verilog/rtl/CaravelTopLevel.v

          pushd soc-dtu-2025
          
          git checkout main
          git pull origin main

          if git diff --quiet; then
              echo "No changes to commit"
              exit 0
          fi
          
          git add verilog/rtl/CaravelTopLevel.v
          git commit -m "Update CaravelTopLevel.v"
          git push origin main
          
          popd